# Generated by Django 6.1 on 2026-08-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_remove_register_first_name_remove_register_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="role",
            field=models.CharField(
                choices=[
                    ("candidate", "Job Seeker / Candidate"),
                    ("employer", "Employer / Recruiter"),
                ],
                default="candidate",
                max_length=20,
            ),
        ),
    ]
