# Generated by Django 6.1 on 2026-08-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_register_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="phone",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
