# Generated by Django 6.1 on 2026-08-28 17:44

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_alter_register_phone_alter_register_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerUser",
            fields=[],
            options={
                "verbose_name": "🏢 Employer",
                "verbose_name_plural": "🏢 2. Employers (Recruiters)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("job.register",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="JobSeekerUser",
            fields=[],
            options={
                "verbose_name": "🧑\u200d💼 Job Seeker",
                "verbose_name_plural": "🧑\u200d💼 1. Job Seekers (Candidates)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("job.register",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
